name: ROS 2 CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. ROS 2 環境をセットアップ
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.3
        with:
          distribution: foxy

      # 3. 依存関係のインストール
      - name: Install dependencies
        run: |
          sudo apt update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # 4. colcon ビルド
      - name: Build the workspace
        run: |
          colcon build

      # 5. テストの実行
      - name: Run tests
        run: |
          colcon test

